name: Deploy App

on:
  workflow_call:
    inputs:
      event_type:
        description: "Remote workflow event type"
        type: string
        required: false
        default: 'app_deploy_v2'
      infra_repo:
        description: "Remote infrastructure repo"
        required: false
        type: string
        default: 'orbitmi/infra-live-apps'
      deploy_environment:
        description: "Environment where app will be deployed"
        required: false
        type: string
        default: "dev"
      service_name:
        description: "Name or array of service name to be deployed"
        required: true
        type: string
      app_version:
        description: "Version"
        required: true
        type: string
      is_finished:
        description: "Wait for called event to finish"
        required: false
        type: boolean
        default: true
    secrets:
      gh_token:
        required: true

permissions:
  id-token: none


jobs:
  prepare_data:
    name: 'Prepare data for deployment'
    runs-on: self-hosted
    steps:
      - name: Get service name
        id: get_service_name
        run: |
          echo ::set-output name=service_name::$(echo -n ${{ inputs.service_name }} | jq -cRs 'split(", ")')
    outputs:
      service_name: ${{ steps.get_service_name.outputs.service_name }}


  deploy:
    name: Run Repository Dispatcher
    runs-on: ubuntu-latest
    needs: [prepare_data]
    strategy:
      max-parallel: 1
      matrix:
        service_name: ${{ fromJson(needs.prepare_data.outputs.service_name) }}
    steps:
      - name: Get repo data
        id: repo_data
        uses: orbitmi/gha-utils/actions/repo-data@v0.3.1
      - name: Trigger deploy
        uses: orbitmi/gha-utils/actions/repo-dispatch@v0.3.1
        with:
          gh_token: ${{ secrets.gh_token }}
          repository: ${{ inputs.infra_repo }}
          event_type: ${{ inputs.event_type }}
          client_payload: '{"env": "${{ inputs.deploy_environment }}", "version": "${{ inputs.app_version }}", "name": "${{ matrix.service_name }}"}'
          wait: ${{ inputs.is_finished }}