name: Prepare App Release

on:
  workflow_call:
    inputs:
      release_type:
        description: Release Type
        required: true
        type: string
      config_repo:
        description: "Remote config repo"
        required: false
        type: string
        default: 'orbitmi/infra-config'
    secrets:
      gh_token:
        required: true

permissions:
  contents: write

jobs:
  run:
    name: Prepare '${{ inputs.release_type }}' version
    runs-on: ubuntu-latest
    steps:
      # Checkout the source code first
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.gh_token }}

      # Checkout the configuration repo in the subdir `infra-config`
      - name: Checkout infra config
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.config_repo }}
          path: 'infra-config'
          token: ${{ secrets.gh_token }}
      - name: Prepare App for Release
        id: artifact
        uses: orbitmi/gha-utils/actions/init-release@v0.3.7
        with:
          release_type: ${{ inputs.release_type }}
          config_dir: 'infra-config'
