name: 'Artifact CI'

on:
  workflow_call:
    inputs:
      push_image:
        description: 'Whether to push image to container registry or not?'
        required: false
        type: string
        default: 'true'
      platform:
        description: "Change the platform on which runner will be working on "
        required: true
        type: string
        default: ubuntu-latest
      service_name:
        description: "Name or array of service name to be deployed"
        required: true
        type: string
        default: "service1" # or "service1, service2" 
      deploy_environment:
        description: "Environment where app will be deployed"
        required: false
        type: string
        default: "dev"
      infra_repo:
        description: "Remote infrastructure repo"
        required: true
        type: string
      event_type:
        description: "Remote workflow event type"
        required: false
        type: string
        default: "app_deploy_v2"
      app_build_dir:
        description: "Directory where solution file is stored"
        required: false
        type: string
        default: "src/"
    secrets:
      gh_token:
        description: 'Github access token'
        required: true      
      sonar_token:
        description: 'Sonarcloud access token'
        required: true

jobs:
  build_push:
    name: 'Build, publish and verify'
    runs-on: ${{ inputs.platform }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
          token:  ${{ secrets.gh_token }}
      - name: Get repo data
        id: repo_data
        uses: htec-infra/gha-utils/actions/repo-data@v0.3.1
      - name: Build and push container image
        id: container_ops
        uses: htec-infra/gha-utils/actions/container-ops@v0.3.1
        with:
          push_image: "${{ inputs.push_image }}"
      - name: Comment PR
        id: comment_pr
        uses: htec-infra/gha-utils/actions/comment-pr@v0.3.1
        with:
          gh_token: "${{ inputs.gh_token }}"

  setup_matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Setup matrix
        id: setup_matrix
        run: |
          echo ::set-output name=matrix::$(echo -n ${{ inputs.service_name }} | jq -cRs 'split(", ")')
    outputs:
      matrix: ${{ steps.setup_matrix.outputs.matrix }}

  auto_deploy:
    name: Auto Deploy (Dev Only)
    needs: [build_and_publish, setup_matrix]
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        service_name: ${{ fromJson(needs.setup_matrix.outputs.matrix) }}
    if: contains(needs.build_and_publish.outputs.app_version, 'alpha')
    steps:
      - name: Trigger
        uses: htec-infra/gha-utils/actions/repo-dispatch@v0.3.1
        with:
          gh_token: ${{ secrets.gh_token }}
          repository: ${{ inputs.infra_repo }}
          event_type: ${{ inputs.event_type }}
          client_payload: '{"env": "${{ inputs.deploy_environment }}", "version": "${{ needs.build_and_publish.outputs.app_version }}", "name": "${{ matrix.service_name }}"}'
          wait: true

  # sonarcloud:
  #   name: Code Quality check
  #   uses: htec-infra/gha-tbd/.github/workflows/sonarscan-dotnet.yml@v0.7.0
  #   with:
  #     build_dir: ${{ inputs.app_build_dir }}
  #   secrets:
  #     sonar_token: ${{ secrets.sonar_token }}
  #     gh_token: ${{ secrets.gh_token }}
